{"name":"Dataflow 1","ppdf:dataflowId":"7877656a-4b67-4dbd-be7d-5f8ddfbafc23","ppdf:owner":{"tenantId":"b30f4b44-46c6-4070-9997-f87b38d4771c","userId":"9bf04242-0d89-4458-9f50-2a2799bf7924"},"ppdf:fastCopy":true,"version":"1.0","culture":"en-GB","modifiedTime":"2025-11-07T19:26:05.7800268+00:00","ppdf:outputFileFormat":"Parquet","pbi:mashup":{"fastCombine":false,"allowNativeQueries":true,"queriesMetadata":{"Query":{"queryId":"507c32c8-4f4a-44f1-86c3-b1533420d2e2","queryName":"Query","loadEnabled":true},"missing_trim_grouping (2)":{"queryId":"6a65b434-9dc6-4d87-8971-6d3d253816a2","queryName":"missing_trim_grouping (2)","loadEnabled":true},"Grouping":{"queryId":"df088531-6c0b-45b5-a348-24982f79df18","queryName":"Grouping","loadEnabled":true},"AvgRating_PerAuthor":{"queryId":"befaa512-c96f-4658-81c8-95a3e334967e","queryName":"AvgRating_PerAuthor","loadEnabled":true}},"document":"section Section1;\r\nshared Query = let\r\n  Source = AzureStorage.DataLake(\"https://goodreadsreviews60314097.dfs.core.windows.net/\"),\r\n  #\"From Value\" = Table.FromValue(Source),\r\n  #\"Remove Columns\" = Table.RemoveColumns(#\"From Value\", Table.ColumnsOfType(#\"From Value\", {type table, type record, type list, type nullable binary, type binary, type function}))\r\nin\r\n  #\"Remove Columns\";\r\nshared #\"missing_trim_grouping (2)\" = let\n  Source = AzureStorage.DataLake(\n    \"https://goodreadsreviews60314097.dfs.core.windows.net/lakehouse/gold/curated_reviews/\",\n    [HierarchicalNavigation=true]\n  ),\n  DeltaTable = DeltaLake.Table(Source),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(DeltaTable, {{\"review_id\", type text}, {\"book_id\", Int64.Type}, {\"author_id\", Int64.Type}}),\r\n  #\"Removed blank rows\" = Table.SelectRows(#\"Changed column type\", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {\"\", null}))),\r\n  #\"Added custom\" = Table.TransformColumnTypes(Table.AddColumn(#\"Removed blank rows\", \"review_length\", each if [review_text] = null \r\nthen 0 \r\nelse Text.Length(Text.Trim([review_text]))), {{\"review_length\", Int64.Type}}),\r\n  #\"Filtered rows\" = Table.SelectRows(#\"Added custom\", each [review_length] > 10),\r\n  #\"Trimmed text\" = Table.TransformColumns(#\"Filtered rows\", {{\"title\", each Text.Trim(_), type nullable text}, {\"name\", each Text.Trim(_), type nullable text}, {\"review_text\", each Text.Trim(_), type nullable text}}),\r\n  #\"Capitalized each word\" = Table.TransformColumns(#\"Trimmed text\", {{\"title\", each Text.Proper(_), type nullable text}}),\r\n  #\"Capitalized each word 1\" = Table.TransformColumns(#\"Capitalized each word\", {{\"name\", each Text.Proper(_), type nullable text}}),\r\n  #\"Added custom 1\" = Table.TransformColumnTypes(Table.AddColumn(#\"Capitalized each word 1\", \"WordCount\", each List.Count(List.Select(Text.Split(Text.Trim([review_text]), \" \"), each _ <> \"\"))), {{\"WordCount\", Int64.Type}})\nin\n  #\"Added custom 1\";\r\nshared Grouping = let\n  Source = AzureStorage.DataLake(\n    \"https://goodreadsreviews60314097.dfs.core.windows.net/lakehouse/gold/curated_reviews/\",\n    [HierarchicalNavigation=true]\n  ),\n  DeltaTable = DeltaLake.Table(Source),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(DeltaTable, {{\"review_id\", type text}, {\"book_id\", Int64.Type}, {\"author_id\", Int64.Type}}),\r\n  #\"Removed blank rows\" = Table.SelectRows(#\"Changed column type\", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {\"\", null}))),\r\n  #\"Added custom\" = Table.TransformColumnTypes(Table.AddColumn(#\"Removed blank rows\", \"review_length\", each if [review_text] = null \r\nthen 0 \r\nelse Text.Length(Text.Trim([review_text]))), {{\"review_length\", Int64.Type}}),\r\n  #\"Filtered rows\" = Table.SelectRows(#\"Added custom\", each [review_length] > 10),\r\n  #\"Trimmed text\" = Table.TransformColumns(#\"Filtered rows\", {{\"title\", each Text.Trim(_), type nullable text}, {\"name\", each Text.Trim(_), type nullable text}, {\"review_text\", each Text.Trim(_), type nullable text}}),\r\n  #\"Capitalized each word\" = Table.TransformColumns(#\"Trimmed text\", {{\"title\", each Text.Proper(_), type nullable text}}),\r\n  #\"Capitalized each word 1\" = Table.TransformColumns(#\"Capitalized each word\", {{\"name\", each Text.Proper(_), type nullable text}}),\r\n  #\"Added custom 1\" = Table.TransformColumnTypes(Table.AddColumn(#\"Capitalized each word 1\", \"WordCount\", each List.Count(List.Select(Text.Split(Text.Trim([review_text]), \" \"), each _ <> \"\"))), {{\"WordCount\", Int64.Type}}),\r\n  #\"Grouped rows\" = Table.Group(#\"Added custom 1\", {\"book_id\"}, {{\"avg_rating\", each List.Average([rating]), type nullable number}, {\"review_count\", each Table.RowCount(_), Int64.Type}})\nin\n  #\"Grouped rows\";\r\nshared AvgRating_PerAuthor = let\n  Source = AzureStorage.DataLake(\n    \"https://goodreadsreviews60314097.dfs.core.windows.net/lakehouse/gold/curated_reviews/\",\n    [HierarchicalNavigation=true]\n  ),\n  DeltaTable = DeltaLake.Table(Source),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(DeltaTable, {{\"review_id\", type text}, {\"book_id\", Int64.Type}, {\"author_id\", Int64.Type}}),\r\n  #\"Removed blank rows\" = Table.SelectRows(#\"Changed column type\", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {\"\", null}))),\r\n  #\"Added custom\" = Table.TransformColumnTypes(Table.AddColumn(#\"Removed blank rows\", \"review_length\", each if [review_text] = null \r\nthen 0 \r\nelse Text.Length(Text.Trim([review_text]))), {{\"review_length\", Int64.Type}}),\r\n  #\"Filtered rows\" = Table.SelectRows(#\"Added custom\", each [review_length] > 10),\r\n  #\"Trimmed text\" = Table.TransformColumns(#\"Filtered rows\", {{\"title\", each Text.Trim(_), type nullable text}, {\"name\", each Text.Trim(_), type nullable text}, {\"review_text\", each Text.Trim(_), type nullable text}}),\r\n  #\"Capitalized each word\" = Table.TransformColumns(#\"Trimmed text\", {{\"title\", each Text.Proper(_), type nullable text}}),\r\n  #\"Capitalized each word 1\" = Table.TransformColumns(#\"Capitalized each word\", {{\"name\", each Text.Proper(_), type nullable text}}),\r\n  #\"Grouped rows\" = Table.Group(#\"Capitalized each word 1\", {\"name\"}, {{\"avg_author_rating\", each List.Average([rating]), type nullable number}})\nin\n  #\"Grouped rows\";\r\n","connectionOverrides":[{"path":"https://goodreadsreviews60314097.dfs.core.windows.net/","kind":"AzureDataLakeStorage","provider":"CdsA","authenticationKind":null,"environmentName":null,"apiName":null,"connectionName":"{\"kind\":\"AzureDataLakeStorage\",\"path\":\"https://goodreadsreviews60314097.dfs.core.windows.net/\"}","audience":null},{"path":"Lakehouse","kind":"Lakehouse","provider":"CdsA","authenticationKind":null,"environmentName":null,"apiName":null,"connectionName":"{\"kind\":\"Lakehouse\",\"path\":\"Lakehouse\"}","audience":null}],"trustedConnections":[{"path":"Lakehouse","kind":"Lakehouse","provider":"CdsA","authenticationKind":null,"environmentName":null,"apiName":null,"connectionName":"{\"kind\":\"Lakehouse\",\"path\":\"Lakehouse\"}","audience":null}]},"entities":[{"$type":"LocalEntity","name":"Query","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Query.parquet"},"annotations":[{"name":"ppdf:entityKeys","value":"[{\"columns\":[\"Folder Path\",\"Name\"]}]"}],"attributes":[{"name":"Name","dataType":"string"},{"name":"Extension","dataType":"string"},{"name":"Date accessed","dataType":"dateTime"},{"name":"Date modified","dataType":"dateTime"},{"name":"Date created","dataType":"dateTime"},{"name":"Folder Path","dataType":"string"}]},{"$type":"LocalEntity","name":"missing_trim_grouping (2)","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"missing_trim_grouping%20%282%29.parquet"},"annotations":[{"name":"ppdf:entityKeys","value":"[]"}],"attributes":[{"name":"review_id","dataType":"string"},{"name":"book_id","dataType":"int64"},{"name":"title","dataType":"string"},{"name":"author_id","dataType":"int64"},{"name":"name","dataType":"string"},{"name":"user_id","dataType":"string"},{"name":"rating","dataType":"int64"},{"name":"review_text","dataType":"string"},{"name":"review_length","dataType":"int64"},{"name":"WordCount","dataType":"int64"}]},{"$type":"LocalEntity","name":"Grouping","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Grouping.parquet"},"annotations":[{"name":"ppdf:entityKeys","value":"[{\"columns\":[\"book_id\"]}]"}],"attributes":[{"name":"book_id","dataType":"int64"},{"name":"avg_rating","dataType":"double"},{"name":"review_count","dataType":"int64"}]},{"$type":"LocalEntity","name":"AvgRating_PerAuthor","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"AvgRating_PerAuthor.parquet"},"annotations":[{"name":"ppdf:entityKeys","value":"[{\"columns\":[\"name\"]}]"}],"attributes":[{"name":"name","dataType":"string"},{"name":"avg_author_rating","dataType":"double"}]}]}